name: rnim CI
on:
  push:
    paths:
      - 'tests/**'
      - 'src/**'
      - 'rnim.nimble'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'tests/**'
      - 'src/**'
      - 'rnim.nimble'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [version-1-6, devel]
        target: [linux] #, macos, windows]
        include:
          - target: linux
            builder: ubuntu-18.04
        #  - target: macos
        #    builder: macos-10.15
        #  - target: windows
        #    builder: windows-2019
    name: '${{ matrix.target }} (${{ matrix.branch }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: rnim

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.branch }}

      - name: Install dependencies (Ubuntu)
        if: ${{matrix.target == 'linux'}}
        run: |
          sudo apt-get update
          sudo apt-get install r-base

      - name: Install dependencies (OSX)
        if: ${{matrix.target == 'macos'}}
        run: |
          brew install r

      - name: Setup MSYS2 (Windows)
        if: ${{matrix.target == 'windows'}}
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: base-devel git mingw-w64-x86_64-toolchain

      # how to install with msys2?
      #- name: Install dependencies (Windows)
      #  if: ${{matrix.target == 'windows'}}
      #  shell: msys2 {0}
      #  run: |
      #    pacman -Syu --noconfirm
      #    pacman -S --needed --noconfirm ???

      - name: Setup nimble & deps
        shell: bash
        run: |
          cd rnim
          nimble refresh -y
          nimble install -y

      - name: Run tests (Linux & Mac)
        if: ${{matrix.target != 'windows'}}
        shell: bash
        run: |
          cd rnim
          nimble -y test

      - name: Run tests (Windows)
        if: ${{matrix.target == 'windows'}}
        shell: msys2 {0}
        run: |
          cd rnim
          nimble -y test

      - name: Build docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.target == 'linux' && matrix.branch == 'devel'
        shell: bash
        run: |
          cd rnim
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --path="." --outdir:docs \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            src/rnim.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.target == 'linux' && matrix.branch == 'devel'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: rnim/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
